[package]
name = "hoard-admin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hoard-admin"
path = "src/main.rs"

[dependencies]
hoard-core = { path = "../hoard-core" }
hoard-server = { path = "../hoard-server" }

tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
time = { version = "0.3", features = ["serde", "formatting", "macros"] }
uuid = { workspace = true }
rpassword = "7"
regex = { workspace = true }
reqwest = { workspace = true }
serde_yaml = { workspace = true }
indicatif = { workspace = true }
